### ISSUE TITLE
Lien de partage Twitter

### ISSUE THREAD

**Issue by PierreAmmeloot** [WildCodeSchool/Lyon-0917-MarketingAutomation#305]
Le lien actuel : 
`
<a href=https://twitter.com/share?url= http://comparer.pro/logiciels/koban-marketing &via=Marketing_automation" target="_blank" rel="nofollow" class="mdi mdi-twitter mdi-24px mdi-light hidden social"></a>`

Mettre via "pierre_a" et enlever l'espace entre l'URL et le via. ;-)

**Comment by PierreAmmeloot** [comment]
C'est sur la version mobile, il y a aussi un espace avant le http:// :-)

**Comment by AR6A** [comment]
ok fait
