### ISSUE TITLE
Meta description - page logiciel

### ISSUE THREAD

**Issue by PierreAmmeloot** [WildCodeSchool/Lyon-0917-MarketingAutomation#318]
Le code de la méta description d'une page logiciel ressemble à ceci

`<meta name="description" content=" NextUser &lt;p&gt;NextUser est une plate-forme de marketing ouverte pour re. "/>
` 
Est-il possible de prendre le contenu de la page et de cleaner les entités HTML avant ?
Mettre 350 signes dans la balise.

**Comment by al2b** [comment]
On supprime la meta description

**Comment by al2b** [comment]
ok
