### ISSUE TITLE
Meta description - page détail tag

### ISSUE THREAD

**Issue by PierreAmmeloot** [WildCodeSchool/Lyon-0917-MarketingAutomation#319]
Sur le page de détail d'un tag, par exemple : http://comparer.pro/tag/envoi-sms
La meta description ressemble à ceci : 
`<meta name="description" content=" Compare.pro vous permet de chercher et comparer tous les logiciels de marketing automation du marché."/>
`

Mettre le contenu de la page et non un texte générique.
Limiter à 350 caractères.

**Comment by al2b** [comment]
Ok.
Et si les champs sont vides on prend quoi ?

**Comment by PierreAmmeloot** [comment]
Dans ce cas une balise description vide ou pas de balise description cela me va. :-)

**Comment by al2b** [comment]
ok. Pour les booleans qui sont des tags, tu as mis une balise <p> dans le fichier yaml pour toutes les descriptions, donc ça ne sera jamais vide

**Comment by al2b** [comment]
fait
