### ISSUE TITLE
Bug - page tag Envoi de SMS

### ISSUE THREAD

**Issue by PierreAmmeloot** [WildCodeSchool/Lyon-0917-MarketingAutomation#320]
La page http://comparer.pro/tag/envoi-sms n'affiche aucun logiciel alors que la page listing tag en annonce 12.

**Comment by al2b** [comment]
Haha, bien vu !
En fait, le slug de la propriété "Envoi SMS" est le même que pour le tag "SMS" qu'on a créé. 
Le conflit est de notre fait, car le "faux" tag SMS a le même slug, ce ne sera pas le cas quand on aura les datas finales. En revanche, nous allons le rajouter dans le ReadMe pour éviter que cela se produise.

**Comment by al2b** [comment]
Ticket fermé car il n'y a plus de tag avec ce nom dans la "vraie" base
