### ISSUE TITLE
Logos logiciels

### ISSUE THREAD

**Issue by PierreAmmeloot** [WildCodeSchool/Lyon-0917-MarketingAutomation#322]
Le logos des logiciels manquants sont en PJ.

[logos.zip](https://github.com/WildCodeSchool/Lyon-0917-MarketingAutomation/files/1628256/logos.zip)

**Comment by al2b** [comment]
manque : 
Lead Liaison
Ez Marketing
blueshift
agile CRM

Sinon c'est tout bon, merci

**Comment by PierreAmmeloot** [comment]
Les voici : 

![agile-crm](https://user-images.githubusercontent.com/4603318/34983827-1899afc4-faaf-11e7-801e-5a42ae83e4e8.png)
![lead-liaison](https://user-images.githubusercontent.com/4603318/34983832-1b986fee-faaf-11e7-9521-0d7e7c64157c.png)
![ez-marketing](https://user-images.githubusercontent.com/4603318/34983846-2aa624a4-faaf-11e7-9e61-ea6e10d6e9c7.png)
![blueshift](https://user-images.githubusercontent.com/4603318/34983856-30242b60-faaf-11e7-9c0b-999d3d32602f.png)

**Comment by al2b** [comment]
@PierreAmmeloot tu peux me les zipper ? Parce que là je perds le nom du fichier et je sais pas à quoi ça correspond du coup :/
Merci d'avance

**Comment by PierreAmmeloot** [comment]
[logos.zip](https://github.com/WildCodeSchool/Lyon-0917-MarketingAutomation/files/1634577/logos.zip)

**Comment by al2b** [comment]
Fait
