### ISSUE TITLE
Code HTML page d'accueil invalide W3C

### ISSUE THREAD

**Issue by PierreAmmeloot** [WildCodeSchool/Lyon-0917-MarketingAutomation#324]
Est-il possible de corriger le code HTML de la page d'accueil pour qu'il passe le validateur du W3C ?
https://validator.w3.org/nu/?doc=http%3A%2F%2Fcomparer.pro%2F

**Comment by PiReux** [comment]
Done. A revérifier une fois cette version sur le serveur
