### ISSUE TITLE
Code HTML page logiciel invalide W3C

### ISSUE THREAD

**Issue by PierreAmmeloot** [WildCodeSchool/Lyon-0917-MarketingAutomation#325]
Le code HTML de la page http://comparer.pro/logiciels/mautic-org est invalide W3C est-il possible de le corriger pour qu'il soit valide ?
https://validator.w3.org/nu/?doc=http%3A%2F%2Fcomparer.pro%2Flogiciels%2Fmautic-org

**Comment by PiReux** [comment]
Done. A revérifier une fois sur le serveur

**Comment by PiReux** [comment]
@PierreAmmeloot :attention dans ton fichier excel, dans "cout de configuration" tes balises html sont mal fermées. Ca resort au test W3C. Le reste est bien corrigé et devrait ne pas sortir d'erreur à la prochaine version :)
