### ISSUE TITLE
Page versus : supprimer lien vers sites web

### ISSUE THREAD

**Issue by PierreAmmeloot** [WildCodeSchool/Lyon-0917-MarketingAutomation#328]
Sur une page de versus, par exemple http://comparer.pro/comparatifs/id-contact_vs_limber, supprimer la ligne "Site web" pour les deux fiches. Je souhaite que le seul lien sortant vers le site de l'éditeur provienne de sa fiche. ;-)

**Comment by al2b** [comment]
fait
