### ISSUE TITLE
Bug : page comparatif champs sensible à la casse

### ISSUE THREAD

**Issue by PierreAmmeloot** [WildCodeSchool/Lyon-0917-MarketingAutomation#329]
Sur la page http://comparer.pro/comparatifs quand je commence à chercher "limber" je n'ai pas d'auto-complétion, alors qu'avec "Limber" j'ai bien un résultat. Rendre le champs insensible à la casse.

**Comment by al2b** [comment]
c'est fait, ça fait parti d'un lot de bugs liés au passage Mysql / Postgresql. On met à jour lundi

**Comment by PiReux** [comment]
done
