### ISSUE TITLE
Bug : page comparatif en doublon

### ISSUE THREAD

**Issue by PierreAmmeloot** [WildCodeSchool/Lyon-0917-MarketingAutomation#330]
Si je vais sur : http://comparer.pro/comparatifs/limber_vs_id-contact
Et sur : http://comparer.pro/comparatifs/id-contact_vs_limber

J'ai le même contenu, est-il possible de rediriger l'une des deux vers l'autre ?

**Comment by al2b** [comment]
On s'était mis d'accord sur une gestion par balise canonical et non en redirection. 
Sur ces deux pages, il y a la même canonical : 

<link rel="canonical" href="http://comparer.pro/comparatifs/id-contact_vs_limber" />

 Pourquoi canonical au lieu d'une redirection : 
- on surcharge pas le htaccess de beaucoup de redirections,
- on ne frustre pas l'utilisateur qui choisit le sens de comparaison de son choix et le retrouve à l'affichage

Est ce qu'on est tjs ok ?

**Comment by PierreAmmeloot** [comment]
Ok merci @al2b pour ton retour, cela me va parfaitement. ;-)

**Comment by al2b** [comment]
ok, super, merci

**Comment by al2b** [comment]
Je ferme l'issue pour le suivi
