### ISSUE TITLE
Bug : si champs "commentaire" vide = pas de section dans la page

### ISSUE THREAD

**Issue by PierreAmmeloot** [WildCodeSchool/Lyon-0917-MarketingAutomation#331]
Si le champs "commentaire" du fichier CSV est vide alors le titre "Notre commentaire sur {logiciel}" et sa section ne doivent pas apparaitre dans la fiche logiciel. 
Actuellement le titre et la section s'affiche, par exemple sur http://comparer.pro/logiciels/id-contact

**Comment by PiReux** [comment]
done
