### ISSUE TITLE
Robots.txt

### ISSUE THREAD

**Issue by PierreAmmeloot** [WildCodeSchool/Lyon-0917-MarketingAutomation#332]
Le contenu du robots.txt actuel : http://comparer.pro/robots.txt
Je pense que nous pouvons autoriser l'indexation du contenu. Qu'en pensez-vous ?

**Comment by al2b** [comment]
C'est toi qui voit. On a mis des "faux" tags, donc il faudrait qu'on les supprime avant qu'on autorise le robot à passer.

**Comment by PierreAmmeloot** [comment]
@al2b en effet attendons que le contenu soit propre. ;-)
