### ISSUE TITLE
Page logiciel : afficher puce et numérotation des listes

### ISSUE THREAD

**Issue by PierreAmmeloot** [WildCodeSchool/Lyon-0917-MarketingAutomation#333]
Sur une fiche http://comparer.pro/logiciels/net-results dans les sections "les plus" et "les moins" laisser les listes à puces (ul>li) et listes numéroté (ol>li) s'afficher.

Dans main.css il y a une directive:
```
li {
     list-style: none; 
}
```

A transformer en : 
```
li {
    /* list-style: none; */
}
```
Vérifier l'impact.

De plus j'aimerais que le texte soit aligné à gauche dans ce cas.

**Comment by PierreAmmeloot** [comment]
Les titres des sections sont à passer en minuscule :  
Les PLUS > Les plus
Les MOINS > Les moins

**Comment by PierreAmmeloot** [comment]
Idéalement les puces et listes numérotés doivent pouvoir être utilisé dans les champs de présentation du logiciels et champs de description.

**Comment by al2b** [comment]
ok
