### ISSUE TITLE
Filtres de prix

### ISSUE THREAD

**Issue by PierreAmmeloot** [WildCodeSchool/Lyon-0917-MarketingAutomation#336]
Il y a deux version pour le filtre de prix:

V1
Il y a un champs input dans laquelle l'internaute peux préciser un prix maximum.
Tous les logiciels ayant un prix plus faible que le prix indiqués + tous les logiciel n'ayant pas de prix sont affichés. Les autres sont cachés.

V2
Il y a deux champs : une liste déroulante avec deux valeurs (min et max) + le champs input comme en V1.
Dans le cas ou l'internaute choisis la valeur max et met un prix cela fonctionne comme en V1.
Dans le cas ou l'internaute choisis la valeur min et met un prix cela fonctionne comme ceci : seul les logiciels ayant un prix plus élevé et les logiciels n'ayant pas de prix restent affichés.

**Comment by al2b** [comment]
V1 : done
