### ISSUE TITLE
Filtres moteur de recherche

### ISSUE THREAD

**Issue by PierreAmmeloot** [WildCodeSchool/Lyon-0917-MarketingAutomation#356]
Les filtres sont un peu trop collé au titre du filtre, voir PJ : 
<img width="349" alt="capture d ecran 2018-01-16 a 10 38 28" src="https://user-images.githubusercontent.com/4603318/34982033-84ece8ea-faa9-11e7-9168-0723a6c5ca22.png">

**Comment by PierreAmmeloot** [comment]
Peut-on imaginer avoir le nombre de logiciels concernés à côté de chaque critère ?

**Comment by al2b** [comment]
@PiReux est sur le coup pour le css du filtre, en fait tout a été modifié suite à l'ajout des accordéons dans les pages softwares unique et comparatifs. 
Pour le nombre de logiciels concernés à côté de chaque critère, on s'est dit exactement la même chose ce matin ! Je propose de le mettre dans la file "good to have", c'est quelque chose qu'on peut faire facilement à condition de factoriser avant notre code

**Comment by PierreAmmeloot** [comment]
@al2b ok pour la file "good to have" ;-)
