### ISSUE TITLE
Critères de recherches

### ISSUE THREAD

**Issue by PierreAmmeloot** [WildCodeSchool/Lyon-0917-MarketingAutomation#375]
Quand je fait cette recherche http://comparer.pro/results_sms
Quand je coche "email" dans les filtres j'ai "mail" dans la ligne de titre en haut.
"Filtres actifs (résultats: 9) : Mail, Page d'atterissage,"

Pourquoi ce n'est pas le même terme ?

**Comment by al2b** [comment]
done

**Comment by al2b** [comment]
fait en prod
