### ISSUE TITLE
CSS : nom des filtres

### ISSUE THREAD

**Issue by PierreAmmeloot** [WildCodeSchool/Lyon-0917-MarketingAutomation#377]
Dans les filtres le nom "Création de segment intelligents" à une mise en page bizarre.

Voir PJ.
<img width="403" alt="capture d ecran 2018-01-16 a 17 13 34" src="https://user-images.githubusercontent.com/4603318/34998918-9a64e862-fae0-11e7-9701-17f069061771.png">

**Comment by PierreAmmeloot** [comment]
Idem pour les éléments de la section "Intégration social média" voir PJ.
<img width="341" alt="capture d ecran 2018-01-16 a 17 13 50" src="https://user-images.githubusercontent.com/4603318/34998944-ab75ec1e-fae0-11e7-8018-d65b8bbc516b.png">

**Comment by PierreAmmeloot** [comment]
Idem pour "Autre fonctionnalités"
<img width="397" alt="capture d ecran 2018-01-16 a 17 14 20" src="https://user-images.githubusercontent.com/4603318/34998968-bdfe0cd6-fae0-11e7-8c26-ff540ed16aa4.png">

**Comment by al2b** [comment]
fait
