### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by PierreAmmeloot** [WildCodeSchool/Lyon-0917-MarketingAutomation#382]
Sur la page http://comparer.pro/listing-tags

Est-ce que les tags : 
- Publication automatique sur Twitter
- Publication automatique Facebook 
- Publication automatique instagram
- Publication automatique Linkedin

N'aurais pas plus de sens à avoir un libellé plus court.
Soit : 
- Publication auto Twitter
- Publication auto Facebook 
- Publication auto Instagram
- Publication auto Linkedin

Soit : 
- Publication Twitter
- Publication Facebook 
- Publication Instagram
- Publication Linkedin

Que préférez-vous ?
Dans tout les cas Instagram avec un "i" majuscule. :-)

**Comment by al2b** [comment]
On préfère la dernière version. On fait la modif.

**Comment by PierreAmmeloot** [comment]
👍

**Comment by al2b** [comment]
fait sur le filtre résultat
