### ISSUE TITLE
Possibilité de cacher une fiche 

### ISSUE THREAD

**Issue by PierreAmmeloot** [WildCodeSchool/Lyon-0917-MarketingAutomation#385]
Certaines fiches sont vides, j'ai des éditeurs qui ne répondent pas à mes sollicitations.
Certaines fiches vont me prendre plus de temps que prévu à compléter.

Est-il possible que j'ajoute une colonne dans le fichier Google Drive pour que la fiche ne soit pas importé ?

**Comment by al2b** [comment]
Oui, on peut réfléchir à des possibilités. On en parle demain ?

**Comment by PierreAmmeloot** [comment]
Oui

**Comment by al2b** [comment]
première colonne qui donne l'instruction : soit c'est ok et on importe, soit c'est vide et on affiche rien. Vaut pour tous les fichiers.

**Comment by al2b** [comment]
Fait
