### ISSUE TITLE
Bandeau cookies

### ISSUE THREAD

**Issue by PierreAmmeloot** [WildCodeSchool/Lyon-0917-MarketingAutomation#388]
Est-il possible d'ajouter un bandeau pour les cookies sur toutes les pages du site ?
Ce bandeau s'affiche une fois par visite.

Exemple CNIL : https://www.cnil.fr/fr/exemple-de-bandeau-cookie

Texte : 

> En poursuivant votre navigation sur ce site, vous acceptez l’utilisation de cookies pour mieux comprendre vos besoins et permettre l'amélioration continue du service proposé et réaliser des statistiques de visites].
> Pour en savoir plus sur les cookies : mentions légales (lien vers la page mentions légales)

**Comment by PierreAmmeloot** [comment]
Je pense que ce script est le plus adapté pour ne pas ré-inventer la roue 
https://cookieconsent.insites.com/

**Comment by AR6A** [comment]
Super j'avais vu des script dans le genre je regarde merci
