### ISSUE TITLE
Homepage : ajout texte sous champs de recherche

### ISSUE THREAD

**Issue by PierreAmmeloot** [WildCodeSchool/Lyon-0917-MarketingAutomation#389]
Est-il possible d'ajouter un boite de contenu en dessous du champs de recherche sur la page d'accueil pour humaniser le site ?

Par exemple : 
> Avec comparer.pro trouvez le logiciel de marketing automation qui correspond à vos besoins.

Qu'en pensez-vous ?

**Comment by al2b** [comment]
On est ok, par contre on le fera avec toi cet après-midi pour valider l'emplacement.

**Comment by PierreAmmeloot** [comment]
Merci

**Comment by al2b** [comment]
@fannyperret : faire des propositions
