### ISSUE TITLE
Article : chiffres autour du développement de la plateforme

### ISSUE THREAD

**Issue by PierreAmmeloot** [WildCodeSchool/Lyon-0917-MarketingAutomation#391]
J'aimerais écrire un article avec des chiffres sur la v1 : nb de logiciels, temps passés desssus, nb de lignes de code, etc.

Que pouvez-vous me donner comme chiffres lié au développement de votre côté ?
Temps passé, nombre de post-it, nombre de ligne de code, etc.

**Comment by al2b** [comment]
Quelques idées à la volée : 
- nombre de user stories 
- nombre de sprint
- nombre de post-it : on peut essayer d'en déduire un :)
- nombre de lignes de code : facile à avoir
