### ISSUE TITLE
Optimiser les requêtes, notamment dans page software

### ISSUE THREAD

**Issue by al2b** [WildCodeSchool/Lyon-0917-MarketingAutomation#397]

**Comment by al2b** [comment]
Page software solo : Anne-Laure
Page Versus : Pierrick
Page Tag listing : Andy 
page Tag solo : Pierrick

**Comment by al2b** [comment]
Software unique : query builder optimisée

**Comment by PiReux** [comment]
2 requests pour TagSolo (booleen en tag )

**Comment by PiReux** [comment]
Versus: query builder optimisée

**Comment by al2b** [comment]
On en parle lundi, on fait un mini-sprint sur le thème "optimiser les performances"

**Comment by al2b** [comment]
Pour la page software, c'est fait : pour booleans et pour les "see also" 
On en est à 4 requêtes et on peut faire encore mieux
