### ISSUE TITLE
Moulinette : Ajouter une barre de progression

### ISSUE THREAD

**Issue by al2b** [WildCodeSchool/Lyon-0917-MarketingAutomation#431]
Dans la mesure où on est passé de 1seconde à environ 20 secondes d'import de données, il est temps de considérer l'ajout d'une barre de progression :D

**Comment by al2b** [comment]
@fannyperret , tu l'as fait ?

**Comment by fannyperret** [comment]
Non c'est Pierrick qui l'a fait et je l'ai juste mis "à tester" pour l'issue

**Comment by al2b** [comment]
@fannyperret : tu peux bien relire l'issue et confirmer stp

**Comment by al2b** [comment]
https://symfony.com/doc/current/components/console/helpers/progressbar.html
