### ISSUE TITLE
Moteur de recherche : autocomplétion

### ISSUE THREAD

**Issue by PierreAmmeloot** [WildCodeSchool/Lyon-0917-MarketingAutomation#436]
Un utilisateur qui a testé le moteur de recherche me remonte que cela manque d'une autocompletion. :-)

**Comment by al2b** [comment]
Dis-nous si tu as une suggestion à ce propos. On en a un peu parlé entre nous, on est pas très convaincu, mais pas non plus réticents.

**Comment by PierreAmmeloot** [comment]
Est-ce possible techniquement ou non ?
