### ISSUE TITLE
Fiche logiciel : mettre en avant le commentaire neutre

### ISSUE THREAD

**Issue by PierreAmmeloot** [WildCodeSchool/Lyon-0917-MarketingAutomation#437]
Remarque utilisateur : 
- Limiter la partie texte de chaque marque
- Bien dissocier la partie qui vient de la marque et notre avis
- Dans page logiciel > lien js « voir plus » 

Actions : 
- est-il possible mettre en avant de façon élégante la partie ou je fait mon commentaire ? Est-ce qu'une card entourant le contenu à du sens ?
- si le texte de présentation du logiciel fait plus de 5 lignes, est-il possible d'avoir un lien "en lire plus" qui ouvre le reste du contenu en JS ? Comme sur certains sites média ?

**Comment by al2b** [comment]
ok, en effet on trouve cette proposition pertinente. On regarde. 

Pour le dépliage du contenu, on pense qu'on peut directement faire ça en css
