### ISSUE TITLE
Page de résultat recherche : ajouté recherches associés

### ISSUE THREAD

**Issue by PierreAmmeloot** [WildCodeSchool/Lyon-0917-MarketingAutomation#442]
Recherche plus fréquente dans SERP
Recherche associé dans SERP

**Comment by al2b** [comment]
Basé sur des "vraies" requêtes clients ? 
Ou c'est des suggestions liées à certains types de requêtes, par exemple : on détecte qu'il y a le mot "mail" dans la recherche, on lui suggère une liste de recherches associés en fonction, qu'on a nous-même déterminé ?

**Comment by PierreAmmeloot** [comment]
Idéalement : basée sur de vraies requêtes ;-)
