### ISSUE TITLE
Changer le titre de la page méthodologie

### ISSUE THREAD

**Issue by PierreAmmeloot** [WildCodeSchool/Lyon-0917-MarketingAutomation#444]
Page méthodologie > lui donner un autre titre, « bonnes pratiques marketing automation », dans le menu mettre seulement "bonnes pratiques"

**Comment by al2b** [comment]
@fannyperret, tu veux prendre l'issue ? 
page "méthodologie" : 
H1 : Bonnes pratiques marketing automation
Changer l'intitulé dans le footer : "Bonnes pratiques" au lieu de méthodologie (actuel)

**Comment by fannyperret** [comment]
Yes


2018-01-25 10:02 GMT+01:00 al2b <notifications@github.com>:
