### ISSUE TITLE
Enrichir page logiciel : logos + témoignages clients

### ISSUE THREAD

**Issue by PierreAmmeloot** [WildCodeSchool/Lyon-0917-MarketingAutomation#446]
Logos des clients qui utilisent 
Témoignages Clients

**Comment by al2b** [comment]
Où dans la page ? 
Combien de logos environ ?

**Comment by PierreAmmeloot** [comment]
Où dans la page : à définir
Combien de logos : potentiellement 5 ou 6. ;-)
