### ISSUE TITLE
Performance du site mobile/desktop

### ISSUE THREAD

**Issue by al2b** [WildCodeSchool/Lyon-0917-MarketingAutomation#459]
https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fcomparer.pro%2F

on a des performances vraiment pas terribles, il faudrait voir ce qu'on peut améliorer ...

**Comment by PiReux** [comment]
C'est vachement interessant en tout cas! Meme si c'est pas ces images la
qui sont spécifiées on va checker la taille des logos au cas ou. et pour la
gestion du cache je t'avoue que je sais pas trop comment on peut s'y
prendre. On a une piste pour delayer le chargement de certains scripts pour
éviter qu'ils chargent avant le contenu du dessus de la ligne de
flottaison, mais c'est tout pour l'instant



2018-01-29 10:31 GMT+01:00 al2b <notifications@github.com>:

**Comment by al2b** [comment]
oui, on demandera à Laurent !
